//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseHotelv2.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public string ReservationID { get; set; }
        public string PropertyID { get; set; }
        public string ClientID { get; set; }
        public string BookingStatus { get; set; }
        public string TimeSegment { get; set; }
        public Nullable<bool> Deposit_Received { get; set; }

        public virtual Property Property { get; set; }
    }
}
